6 validating answers
St0n3k/wordio pull request #22
Opened 2023-05-31 23:29 UTC by rstrzalkowski

* Implemented using external API to check whether words exist in dictionary (polish)
 * Sending answers back to players with check status
 * Created STOMP endpoint to receive votes from players

2023-06-01 18:51 UTC, Msocha19 requested changes

2023-06-01 18:51 UTC, Msocha19 commented on backend/src/main/java/pl/lodz/p/it/zzpj/service/GameRedisService.java
> +    public void sendVotes(PlayerVotesDTO playerVotesDTO, UUID gameID)
Add restriction, so that users can only vote once.

2023-06-01 18:51 UTC, Msocha19 commented on backend/src/main/java/pl/lodz/p/it/zzpj/service/GameRedisService.java
> +    public void sendVotes(PlayerVotesDTO playerVotesDTO, UUID gameID)
Voting should end after a certain amount of time, I don't think it is needed for everyone to vote.

2023-06-08 23:37 UTC, rstrzalkowski commented on backend/src/main/java/pl/lodz/p/it/zzpj/service/GameRedisService.java
> +    public void sendVotes(PlayerVotesDTO playerVotesDTO, UUID gameID)
Fixed in updated PR

2023-06-08 23:38 UTC, rstrzalkowski commented on backend/src/main/java/pl/lodz/p/it/zzpj/service/GameRedisService.java
> +    public void sendVotes(PlayerVotesDTO playerVotesDTO, UUID gameID)
Fixed in updated PR

2023-06-11 17:25 UTC, Lukasz0104 approved these changes

2023-06-11 17:27 UTC, merged